### ISSUE TITLE
Minor Lag

### ISSUE THREAD

**Issue by grekan** [prophecymud/go-prophecy-issues#47] opened 2019-11-30 18:44 UTC
There appears to be very minor lag. Behaviour is inconsistent, so it's not reproducable except by playing a bit. 

I noticed lag so far when:
oocing
Trying to enter a room that was only for priests. 
General lag when walking. 

Lag is about 1-2 seconds. Not consistently reproducable. 

Connected via JMC. Qethia noticed it also, using different client.

**Comment by Ranfir** [comment] 2019-11-30 19:46
I'm seeing this too. Occasionally, 1.6s lag between rooms vs. 0.25s normal movement lag.

![image](https://user-images.githubusercontent.com/58370848/69905326-19ee2300-1380-11ea-81df-722d93c53be9.png)

**Comment by Ranfir** [comment] 2019-11-30 19:49
Also, logging on seems to be a lot laggier vs CProph.

**Comment by anhegofcherek** [comment] 2019-12-11 20:25
Thanks - IOtime on this box is _horrendous_ - I expect this to go away the moment I move it somewhere less terrible!

**Comment by anhegofcherek** [comment] 2020-01-03 11:32
> Also, logging on seems to be a lot laggier vs CProph.

This will be #25 - currently it's doing synchronous DNS lookups without caching...

**Comment by anhegofcherek** [comment] 2020-01-06 23:57
Might try to run it on a healthier box, but it should be notably better since addressing #25

**Comment by Ranfir** [comment] 2020-01-07 23:00
It is noticeably better indeed!

**Comment by Ranfir** [comment] 2020-02-11 18:47
I feel like I've been experiencing occasional lag under two scenarios:
1. On the **second** move (not first) after casting `word of recall`. On the first move, I see approximately 2 seconds of lag from having cast word of recall. On the second move, I see almost 1 second of lag that shouldn't be there.
2. When using the `who` command.

**Comment by grekan** [comment] 2020-02-12 01:56
FWIW - I don't see the same behaviour. Word of recall clearly has lag attached to it, but moving in two different directions afterwards is fluid. Same with word, and then different commands, there's no lag.

**Comment by Ranfir** [comment] 2020-02-12 03:03
I don't get the lag all the time. But when I do notice the lag, it's in those two scenarios.

**Comment by anhegofcherek** [comment] 2022-10-21 22:04
I've not been able to reproduce this, and I suspect it might actually have been the object/saving related slowness from #92 and similar

I appreciate the report but I think I'm going to close this for now unless we can get something more consistent / current - thank you for filing it!

**Closed as completed by anhegofcherek** 2022-10-21 22:04 UTC
