### ISSUE TITLE
Hidden objects show up with (Dark) prefix

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/go-prophecy-issues#72] opened 2019-12-01 03:17 UTC
```
     (Dark) A jug of water is here.
```

Not necessarily a bug, but this behavior seems to occur in GoProph and not in CProph. Reproduce by using the hide command on an object.

**Comment by anhegofcherek** [comment] 2020-01-02 18:29
Nicely found - not sure why that's happening!

**Comment by anhegofcherek** [comment] 2020-01-02 19:23
Specifically, it should be occurring on CProph too...

**Comment by anhegofcherek** [comment] 2020-01-02 20:14
```
    if ( IS_IMMORTAL(ch) && IS_OBJ_STAT(obj, ITEM_VIS_DEATH)     )
        strcat( buf, "(`!VisDeath``) "     );

    if ( IS_OBJ_STAT(obj, ITEM_INVIS)     )
        strcat( buf, "(`$Invis``) "     );
    if ( (IS_AFFECTED(ch, AFF_DETECT_EVIL) || is_affected(ch,gsn_true_sight))
            && IS_OBJ_STAT(obj, ITEM_EVIL)   )
        strcat( buf, "(`1Red Aura``) "  );
    if ( (IS_AFFECTED(ch, AFF_DETECT_GOOD) || is_affected(ch,gsn_true_sight))
            &&  IS_OBJ_STAT(obj,ITEM_BLESS))
        strcat(buf,"(`4Blue Aura``) "     );
    if ( IS_AFFECTED(ch, AFF_DETECT_HIDDEN || is_affected(ch,gsn_true_sight))
            && IS_OBJ_STAT(obj, ITEM_DARK)   )
        strcat( buf, "(`8Dark``) "      );
```

```
You are affected by the following spells:
Spell: true sight     : modifies none by 0 for 3 hours
```

```
stat obj glass
[...]
Short description: (2020 Happy New Year) A glass of champagne
Extra bits: dark bless vis_death
[...]
```

```
(VisDeath) (Blue Aura) A glass of champagne celebrating the 2020 New Years lies here.
```

So, uh...

**Comment by anhegofcherek** [comment] 2020-01-02 20:16
Part of me's tempted to write this off because GoProph is working entirely as expected here, but also I'm confused as to what CProph is doing!

**Comment by anhegofcherek** [comment] 2020-01-04 00:14
@Ranfir Any objections to me closing this, on the grounds that GoProph works as expected, and so this looks like a CProph bug that, despite not understanding the cause of, I seem to have fixed in the port?

**Comment by Ranfir** [comment] 2020-01-04 07:12
Fine by me.

**Comment by Ranfir** [comment] 2020-01-07 23:01
As an after thought, could it be related to the Glowing / Humming flags also not showing up?

**Comment by prophnoran** [comment] 2020-01-08 05:06
I think I can shed some light on the cproph mystery, at least; should perhaps

```
    if ( IS_AFFECTED(ch, AFF_DETECT_HIDDEN || is_affected(ch,gsn_true_sight))
            && IS_OBJ_STAT(obj, ITEM_DARK)   )
```

instead read

```
    if ( (IS_AFFECTED(ch, AFF_DETECT_HIDDEN) || is_affected(ch,gsn_true_sight))
            && IS_OBJ_STAT(obj, ITEM_DARK)   )
```

?

**Comment by anhegofcherek** [comment] 2020-01-08 19:18
@prophnoran Nailed it - well spotted!

In 2017 it turns out that the Go typechecker spotted this for me, but a lot has happened since then...!

```
commit aab22f3a97dc6f664dcd4a9fc4bf3ba12ea720eb
Date:   Thu Dec 28 18:59:55 2017 +0100

    Golang format_obj_to_char (with logic fix for ITEM_DARK!)

diff --git a/src/prophecy/act_info.c b/src/prophecy/act_info.c
```

**Closed as completed by anhegofcherek** 2020-01-08 19:18 UTC
