### ISSUE TITLE
note find shows incorrect indices

### ISSUE THREAD

**Issue by Ranfir** [prophecymud/go-prophecy-issues#73] opened 2019-12-13 16:49 UTC
E.g.
```
change find Anheg
[ 51 ]From:      Anheg To:            All Subject: Code Update
[ 51 ]From:      Anheg To:            All Subject: Code Changes
[ 51 ]From:      Issus To:             pk Subject: Old Clan Halls
[ 51 ]From:      Anheg To:            All Subject: Guardsmen
[ 51 ]From:      Anheg To:            All Subject: Last Reboot
[ 54 ]From:      Anheg To:            All Subject: Code Changes
[ 54 ]From:      Anheg To:            All Subject: Mandorallen/Toth
[ 55 ]From:      Anheg To:            All Subject: Aquest Equipment
[ 56 ]From:      Anheg To:            All Subject: Code Changes
[ 56 ]From:      Anheg To:            All Subject: Code Changes
[ 56 ]From:      Anheg To:            All Subject: Yet More Code Changes
[ 56 ]From:      Anheg To:            All Subject: BP
[ 56 ]From:    Harakan To:            all Subject: Recent Code Changes
[ 57 ]From:      Anheg To:            All Subject: Code Changes
[ 57 ]From:      Anheg To:            All Subject: Stash
[ 57 ]From:      Anheg To:            All Subject: Stash
[ 57 ]From:      Anheg To:            All Subject: Archery
[ 57 ]From:      Anheg To:            All Subject: Bows
[ 57 ]From:      Anheg To:            All Subject: Minor Code Changes
[ 57 ]From:      Anheg To:            All Subject: Recent Reboot-fest
[ 57 ]From:      Anheg To:            All Subject: Saves Code
[ 58 ]From:      Anheg To:            All Subject: Stash
[ 58 ]From:      Anheg To:            All Subject: Socials
[ 58 ]From:      Anheg To:            All Subject: Last Reboot
[ 58 ]From:      Anheg To:    All Builder Subject: Mprogs (including some item loads)
[ 58 ]From:      Anheg To:            All Subject: New Area
[ 58 ]From:      Anheg To:            All Subject: New Area
[ 58 ]From:      Anheg To:            all Subject: Longer Emily Special Scavengers!
[ 59 ]From:      Anheg To:            All Subject: aq disenchant
29 messages with content matching 'Anheg' were found.
```

**Comment by anhegofcherek** [comment] 2019-12-17 22:55
That's odd! I can't reproduce this though... Are you still seeing it / are you able to narrow it down at all please?

**Comment by Ranfir** [comment] 2019-12-19 21:58
Definitely still seeing it. Here's CProph for comparison:

```
change find Anheg
[ 48 ]From:      Anheg To:            All Subject: Recent Code Changes
[ 50 ]From:      Anheg To:            All Subject: Recent Code Changes
[ 53 ]From:      Anheg To:            All Subject: Code Update
[ 54 ]From:      Anheg To:            All Subject: Melcene
[ 55 ]From:      Anheg To:            All Subject: New code changes
[ 56 ]From:      Anheg To:            All Subject: Eq in containers
[ 57 ]From:      Anheg To:            All Subject: Code Update
[ 58 ]From:      Anheg To:            All Subject: Code Changes
[ 59 ]From:      Anheg To:            All Subject: Code changes
[ 60 ]From:      Anheg To:            All Subject: Code Changes
[ 61 ]From:      Anheg To:            All Subject: Code Changes
[ 62 ]From:      Anheg To:            All Subject: Guardsmen
[ 63 ]From:      Anheg To:            All Subject: Last Reboot
[ 67 ]From:      Anheg To:            All Subject: Code Changes
[ 68 ]From:      Anheg To:            All Subject: Safegive
[ 69 ]From:      Anheg To:            All Subject: Mandorallen/Toth
[ 71 ]From:      Anheg To:            All Subject: Aquest Equipment
[ 72 ]From:      Anheg To:            All Subject: Old Aquest Eq
[ 74 ]From:      Anheg To:            All Subject: Code Changes
[ 75 ]From:      Anheg To:            All Subject: Code Changes
[ 76 ]From:      Anheg To:            All Subject: Yet More Code Changes
[ 77 ]From:      Anheg To:            All Subject: BP
[ 78 ]From:    Harakan To:            all Subject: Recent Code Changes
[ 79 ]From:      Anheg To:            All Subject: Re: Recent Code Changes
[ 80 ]From:      Anheg To:            All Subject: Code Changes
[ 81 ]From:      Anheg To:            All Subject: Stash
[ 82 ]From:      Anheg To:            All Subject: Stash
[ 83 ]From:      Anheg To:            All Subject: Lockers
[ 84 ]From:      Anheg To:            All Subject: Archery
[ 85 ]From:      Anheg To:            All Subject: Bows
[ 86 ]From:      Anheg To:            All Subject: Minor Code Changes
[ 87 ]From:      Anheg To:            All Subject: Recent Reboot-fest
[ 88 ]From:      Anheg To:            All Subject: Saves Code
[ 90 ]From:      Anheg To:            All Subject: Stash
[ 91 ]From:      Anheg To:            All Subject: Socials
[ 92 ]From:      Anheg To:            All Subject: Code Changes
[ 93 ]From:      Anheg To:            All Subject: Last Reboot
[ 94 ]From:      Anheg To:            All Subject: Aquest Completion Times
[ 95 ]From:      Anheg To:            All Subject: New Area
[ 96 ]From:      Anheg To:            All Subject: New Area
[ 97 ]From:      Anheg To:            All Subject: Area Updates
[ 98 ]From:      Anheg To:            All Subject: Legions of Neutral Overlord
[ 99 ]From:      Anheg To:            All Subject: Aquest Switch
[100 ]From:      Anheg To:            All Subject: Christmas Code Changes
[101 ]From:      Anheg To:            all Subject: Longer Emily Special Scavengers!
[102 ]From:      Anheg To:            All Subject: Boktor Jail
[103 ]From:      Anheg To:            All Subject: aq disenchant
[104 ]From:      Anheg To:            All Subject: Rppts
```

**Comment by Ranfir** [comment] 2019-12-19 22:08
Also, it seems that not all notes got ported over. Maybe that's related?

## CProph
```
unread
   Prophecy Notes Bulletin.
--------------------------------
[Ttl] [New] [You]
[103] [  0] [  0] : News articles.
[105] [  0] [  0] : Changes.
[  2] [  0] [  0] : Notes.
[  1] [  0] [  0] : Ideas.
[131] [  0] [  0] : Trades.
[338] [  0] [  0] : Qnotes.
[2338] [  0] [  0] : Storyboard.
[ 31] [  0] [  0] : EmNotes.
--------------------------------
```

## GoProph
```
unread
   Prophecy Notes Bulletin.
--------------------------------
[Ttl] [New] [You]
[ 80] [  0] [  0] : News articles.
[ 59] [  0] [  0] : Changes.
[  0] [  0] [  0] : Notes.
[  0] [  0] [  0] : Ideas.
[126] [  0] [  0] : Trades.
[328] [  0] [  0] : Qnotes.
[2059] [  0] [  0] : Storyboard.
[  1] [  1] [  0] : EmNotes.
--------------------------------
```

**Comment by Ranfir** [comment] 2019-12-19 22:16
Okay, here's a better hint: **change list** (below) only shows one of your posts, but **change find Anheg** (from my original post) shows 27, including one to **All Builder** that my character shouldn't be able to see.

```
change list
[  0 ]From:      Nahaz To:            all Subject: Area
[  1 ]From:    Kheldar To:            all Subject: MCCP
[  2 ]From:    Naradas To:            all Subject: Update
[  3 ]From:    Kheldar To:            all Subject: MXP
[  4 ]From:    Naradas To:            all Subject: Violence Timer
[  5 ]From:      Nahaz To:            all Subject: Areas
[  6 ]From:    Kheldar To:            all Subject: helpfiles
[  7 ]From:      Nahaz To:            all Subject: Riva
[  8 ]From:     Porenn To:            all Subject: Some New Stuff
[  9 ]From:    Kheldar To:            all Subject: Announce
[ 10 ]From:    Naradas To:            all Subject: Code Update
[ 11 ]From:    Naradas To:            all Subject: Flame
[ 12 ]From:      Nahaz To:            all Subject: Typos
[ 13 ]From:    Kheldar To:            all Subject: bugfixes
[ 14 ]From:    Kheldar To:            all Subject: bugs
[ 15 ]From:      Nahaz To:            all Subject: Mar Terrin Monastary
[ 16 ]From:      Nahaz To:            all Subject: Areas
[ 17 ]From:    Naradas To:            all Subject: Roleplay Rooms
[ 18 ]From:    Naradas To:            all Subject: Mob Memory and PK Bounties
[ 19 ]From:    Naradas To:            all Subject: Emily
[ 20 ]From:     Mordja To:            all Subject: Demonskin
[ 21 ]From:     Mordja To:            all Subject: Addition
[ 22 ]From:     Mordja To:            all Subject: areas
[ 23 ]From:      Urgit To:            all Subject: Stun/Diminish/Web
[ 24 ]From:      Urgit To:            all Subject: Changes 29/2/04
[ 25 ]From:     Porenn To:            all Subject: Some Small Changes
[ 26 ]From:    Naradas To:            all Subject: The Drasnian Trading Post
[ 27 ]From:    Naradas To:            all Subject: PK Corpse Looting
[ 28 ]From:      Nahaz To:            all Subject: Drasnian Trading Post
[ 29 ]From:      Urgit To:            all Subject: PK Corpse Looting Amendment
[ 30 ]From:       Kail To:            all Subject: WWP Upgrading
[ 31 ]From:      Urgit To:            all Subject: Update 05/04/04
[ 32 ]From:      Kyler To:            all Subject: My Recent Changes
[ 33 ]From:     Drosta To:            all Subject: Clan Helpfiles
[ 34 ]From:      Urgit To:            all Subject: New Areas
[ 35 ]From:      Urgit To:            all Subject: Area Update
[ 36 ]From:     Drosta To:            all Subject: Directions
[ 37 ]From:      Urgit To:            all Subject: New Areas
[ 38 ]From:      Urgit To:            all Subject: Area Update
[ 39 ]From:    Naradas To:            all Subject: NScript
[ 40 ]From:    Naradas To:            all Subject: NScript (2)
[ 41 ]From:      Urgit To:            all Subject: Area Update
[ 42 ]From:    Kheldar To:            all Subject: Update
[ 43 ]From:       Kail To:            all Subject: Standard Penalty: Nochannel
[ 44 ]From:       Kail To:            all Subject: Emily Prizes (Scavenger/FTI)
[ 45 ]From:       Kail To:            all Subject: Addendum: Emily scavenger
[ 46 ]From:     Drosta To:            all Subject: Questionnaire
[ 47 ]From:       Kail To:            all Subject: Emily Prizes
[ 48 ]From:       Kail To:            all Subject: New Area
[ 49 ]From:    Yarblek To:            all Subject: MultiClanning
[ 50 ]From:      Issus To:            all Subject: small LoN change
[ 51 ]From:      Issus To:            all Subject: WWP
[ 52 ]From:      Issus To:            all Subject: Clan change
[ 53 ]From:      Brill To:            all Subject: Area Additions and Updates
[ 54 ]From:      Issus To:            all Subject: New change regarding Lords.
[ 55 ]From:      Brill To:            all Subject: Area Additions and Updates
[ 56 ]From:    Harakan To:            all Subject: Recent Code Changes
[ 57 ]From:    Harakan To:            all Subject: New prize tokens!
[ 58 ]From:      Anheg To:            all Subject: Longer Emily Special Scavengers!
```

**Comment by Ranfir** [comment] 2019-12-19 22:25
Also, **change find** is definitely returning results that I shouldn't be able to see.

```
change find imm
[  0 ]From:      Nahaz To:            all Subject: Area
[  2 ]From:    Naradas To:            imm Subject: An Update
[  2 ]From:    Naradas To:            all Subject: Update
[  5 ]From:      Nahaz To:            all Subject: Areas
[  6 ]From:    Kheldar To:            all Subject: helpfiles
[  8 ]From:     Porenn To:            all Subject: Some New Stuff
[ 13 ]From:    Naradas To:            imm Subject: 'last' command.
[ 23 ]From:    Naradas To:            imm Subject: Pending
[ 24 ]From:      Urgit To:            all Subject: Changes 29/2/04
[ 25 ]From:     Porenn To:            all Subject: Some Small Changes
[ 28 ]From:    Naradas To:            imm Subject: Boring
[ 29 ]From:      Urgit To:            all Subject: PK Corpse Looting Amendment
[ 33 ]From:     Drosta To:            all Subject: Clan Helpfiles
[ 35 ]From:      Urgit To:            all Subject: Area Update
[ 51 ]From:      Anheg To:            All Subject: Code Changes
[ 51 ]From:    Kheldar To:            imm Subject: level
[ 56 ]From:      Anheg To:            All Subject: Code Changes
[ 56 ]From:    Harakan To:            all Subject: Recent Code Changes
[ 57 ]From:    Harakan To:            all Subject: New prize tokens!
[ 58 ]From:    Harakan To:       immortal Subject: Prize token information for immortals
[ 58 ]From:      Anheg To:            All Subject: Last Reboot
21 messages with content matching 'imm' were found.
```

**Comment by anhegofcherek** [comment] 2019-12-24 22:42
Tried with a mortal and yup, totally see what you mean, thank you!

**Comment by anhegofcherek** [comment] 2019-12-25 19:21
Think that should all be fixed now, thanks!

**Closed as completed by anhegofcherek** 2019-12-25 19:21 UTC
